### PR TITLE
Navbar!

### PR DESCRIPTION
**Pull request by Ciuffi**
Mobile:
Screen Shot 2019-09-01 at 6 11 10 PM
and desktop screenshots:
image

The mobile one sometimes doesn't show properly but works once i toggle the top property.. not sure why, help would be appreciated!

Also not totally sure where 2018 will link to once we have the new LHD website up... I guess I'll ask the LHD crew?

### CODE REVIEW

**Comment by Ciuffi** [comment]
closes #9

**Comment by luceliu** [comment]
Looks good but I thought design wanted [this](https://images.app.goo.gl/aBEyj4kka2TWRvxa9) hover effect for the links?
[Seems simple enough](https://www.elegantthemes.com/blog/divi-resources/beautiful-css-hover-effects-you-can-add-to-your-divi-menus)

**Comment by Ciuffi** [comment]
@luceliu I've implemented it, not sure if its the right colour though. otherwise this should be good to go.

**Review by luceliu — APPROVED** [review]
gucci w me if design approves (asked on slack)

**Review by kozr — APPROVED** [review]
Wow it looks amazing!

**Pull request merged**
