### PR TITLE
Added styling for faq session

### LINKED ISSUE #16: Style FAQ section

### PR DESCRIPTION
**Pull request by Eric1015**
closes #16 
I added styling for faq session!

image

mobile version

image

### CODE REVIEW

**Review by Ciuffi — CHANGES_REQUESTED** [review]
Looks really good, but could you add a bit more padding to the bottom of the FAQ? when the FAQ question is opened it seems a bit asymmetrical

**Comment by Eric1015** [comment]
OK. I have added some padding space to it.

**Review by Ciuffi — APPROVED** [review]
beautiful thank you!

**Review by acchiang — APPROVED** [review]
looks good to me! good work

**Pull request merged**
