### PR TITLE
Bulletin

### PR DESCRIPTION
**Pull request by Ciuffi**
add the bulletin under intro

pretty simple, but have a look at the css to make sure it works.

### CODE REVIEW

**Comment by Ciuffi** [comment]
closes #11

**Comment by Ciuffi** [comment]
Desktop:
image
Mobile:
image

**Review by kozr — APPROVED** [review]
It works for me too.

**Review by ianmah — CHANGES_REQUESTED** [review]
the path background is off for me
image

**Comment by Ciuffi** [comment]
@ianmah Could you mention how you were able to reproduce this? It makes debugging a lot easier. 

Maybe use a bug template like:

# Bug🐞: 
The river doesn't match up

# How to reproduce🔁:

Reproduction technique

# Additiona info 🔎: 
Anything else you'd like to share


Thanks!

**Comment by Ciuffi** [comment]
(Or just fix it, that works too)

**Comment by ianmah** [comment]
## Bug🐞: 
The river doesn't match up

## How to reproduce🔁:

Default viewing, screen size 1920x1080 (Chrome, firefox)

**Comment by ianmah** [comment]
should the engineering cairn be in the path/river?

**Comment by luceliu** [comment]
Interesting - cairn placement is different for me too 
image

**Comment by ianmah** [comment]
I don't think we should use a huge bg.svg for the background, maybe we can export the path by itself and place it behind the bulletin section so it's more responsive\

I've exported the bottom path if someone wants to try that?

**Comment by ianmah** [comment]
Didn't have time to test much but lmk if that works

**Comment by luceliu** [comment]
That worked for me @ianmah ! 
image

**Comment by luceliu** [comment]
Unrelated concern: should the bulletin board really be THAT off-center? I know on Figma it's 390px from the left and 368px from the right, but it looks a lot more than that in chrome methinks

**Comment by ianmah** [comment]
I feel like the wood of the bulletin should should be centered

**Review by ianmah — APPROVED** [review]

**Pull request merged**
