### PR TITLE
Header/Hero/Intro Section

### PR DESCRIPTION
**Pull request by ianmah**
completed header section #2 
should be responsive as well

Also made a button component, import by
```
import Button from '~/components/Button.vue'
export default {
  components: {
    Button
  },
```

and use with `<Button title="Your title" url="yoururl.com" />`

### CODE REVIEW

**Review by luceliu — COMMENTED** [review]
is it just me or is it off-center in firefox?

Chrome: image
Firefox: 
image

**Comment by luceliu** [comment]
but looks fine on Firefox Developer edition: 
image

**Comment by Ciuffi** [comment]
This looks really good! lets try to figure out whats going on with firefox

**Comment by ianmah** [comment]
According to Figma the left and right margins are not meant to be equal, however on firefox that looks incorrect

**Comment by Ciuffi** [comment]
Your picture look awesome but it looks like this for me :(

image

**Comment by ianmah** [comment]
Oh dear, what screen dimensions are you using and what browser?

**Comment by ianmah** [comment]
Oh, @Ciuffi someone changed the way I put the strings into Firebase db. <You can try again, it should be fixed I'm not able to reproduce Firefox not being centered>

jk, i think the CMS is messing up the way I put the strings into intro text.

**Review by Ciuffi — APPROVED** [review]
Looks good to me now, I made a small fix. (more like a workaround)

**Pull request merged**
