### PR TITLE
add a 3D snow effect to the main page

### LINKED ISSUE #10: Add 3D snow effect to hero section

### PR DESCRIPTION
**Pull request by Ciuffi**
I'm not sure if this is what was meant, was the snow only for once section or for the whole page?

closes #10

### CODE REVIEW

**Comment by kozr** [comment]
I've asked design on slack. I'll let you know.

**Comment by kozr** [comment]
Yuki said they wanted it only for the landing section.

**Comment by Ciuffi** [comment]
I moved the generation to only happen in intro.vue but it doesn't seem to stop the snow from moving to other components.. hopefully this is fine and as long as it only generates at the top we're good.

**Comment by Ciuffi** [comment]
They want the snow to stop after the intro, not sure how to do that so I'm closing this for now, will come back to it later

**Pull request closed without merging**
