### PR TITLE
Footer

### LINKED ISSUE #7: Implement footer

### PR DESCRIPTION
**Pull request by ianmah**
Let me know if the animation doesn't run smoothly, especially on older phones. Not sure what to change if it is slow though.

TODO: 'code of conduct' and 'become a sponsor' links need to go somewhere

closes #7

### CODE REVIEW

**Review by luceliu — CHANGES_REQUESTED** [review]
image
Right now they're just bouncing up - figma/spec says they should turn white. Looks good otherwise though! + Runs smoothly enough on my iPhone 6s

**Review by luceliu — APPROVED** [review]
o we're keeping the bouncing up? okay

**Comment by ianmah** [comment]
@luceliu I have no idea

**Comment by Ciuffi** [comment]
Maybe we should add some designers to github so we can ping them in these cases

**Review by Ciuffi — APPROVED** [review]
Omg this looks amazing!

**Pull request merged**
