### PR TITLE
Launch sponsor section

### PR DESCRIPTION
**Pull request by Ciuffi**
I think the sponsor section is ready to go!

Currently its controlled by a feature flag, so even if this merges to master the sponsor section won't show up. Once the marketing team has added some sponsors, we'll switch the flag to true and launch this section!

### CODE REVIEW

**Comment by Ciuffi** [comment]
This merge also adds the dockerfile to master branch and adds analytics to the website.

**Review by kozr — APPROVED** [review]

**Comment by kozr** [comment]
tbh I think the nav bar's padding is a bit too large

**Comment by Ciuffi** [comment]
@kozr I see what you mean, probably better to leave it for the next release though

**Review by ianmah — APPROVED** [review]
Has some issues but nothing blocking release. Should create some kind of readme or disclaimer so people don't create issues

Don't like how the images scale up - just make sure people using the cms use large enough images so they don't scale too large (biztech logo is blurry)
image

If someone selects an image for upload, then deletes it, broken image will be uploaded
image

**Pull request merged**
